(load "~/.emacs.d/elpa/linum-relative-20130923.1602/linum-relative.el")
(load "~/.emacs.d/elpa/highline-7.2.2/highline.el")
(require 'linum)
(require 'linum-relative)
(require 'highline)
(global-linum-mode t)
